# Generated by Django 3.0.4 on 2020-03-14 09:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('passenger', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passenger',
            name='date_added',
            field=models.DateField(default=datetime.datetime.now),
        ),
    ]
