# Generated by Django 3.0.4 on 2020-03-14 09:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('passenger', '0002_auto_20200314_0915'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passenger',
            name='date_added',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
